# ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!
# LABEL FOR MERGED ASSEMBLIES #
speciesname: "phlox"
shadow_level: "shallow"

########################
## RNA-SEQ FASTQ FILES #
########################
# fastq input file data ##
fastqDir: "../../fastq_prep/results/trimmed/"
############
## HISAT2 ##
############
Hisat2IndexDir: "/n/holylfs05/LABS/hopkins_lab/Lab/Phlox_assembly_collab/transcriptome/genomes/hisat2/"
Hisat2IndexPrefix: "phlox_flye.v1.0.FINAL"
Hisat2Outdir: "results/hisat2/"
Hisat2SamsortOutdir: "results/hisat2/bams/" 
##########
## STAR ##
#########
StarIndexDir: "/n/holylfs05/LABS/hopkins_lab/Lab/Phlox_assembly_collab/transcriptome/genomes/star/"
StarOutDir: "results/star/"
Star1stPassOutdir: "results/star/star1stpass/" 
Star2ndPassOutdir: "results/star/star2ndpass/"
StarSamsortOutdir: "results/star/bams/" 
#############
# STRINGTIE #
# ###########
StringtieHisat2AssemblyDir: "results/stringtie/hisat2/individual_assemblies/" 
StringtieHisat2MergeDir: "results/stringtie/hisat2/merged_assembly/" 
StringtieStarAssemblyDir: "results/stringtie/star/individual_assemblies/"
StringtieStarMergeDir: "results/stringtie/star/merged_assembly/"
##############
##  SCALLOP ##
#############
ScallopHisat2Dir: "results/scallop/hisat2/"
ScallopHisat2AssemblyDir: "results/scallop/hisat2/individual_assemblies/" 
TacoHisat2Dir: "results/scallop/hisat2/taco/"
ScallopStarDir: "results/scallop/star/"
ScallopStarAssemblyDir: "results/scallop/star/individual_assemblies/"
TacoStarDir: "results/scallop/star/taco/" 
